### ISSUE TITLE
Designing screens

### ISSUE THREAD

**Issue by sachamorgese** [chingu-voyage4/Bears-Team-6#10]
Vladimir has identified these 6 screens to work on. We should split the task and try to figure out a design. Let's use Sketch when possible.

Let's start working on it after finalizing the project details and MVP

**Comment by vladimirlogachev** [comment]
Done everything but voting (just skipped this phase for now) and public profile (which can be intuitively derived from user own profile)

**Comment by sachamorgese** [comment]
I'd like to design some screens as well, so leave the future ones to me

**Comment by vladimirlogachev** [comment]
NP
