### ISSUE TITLE
Set Individual Goals - kev

### ISSUE THREAD

**Issue by sachamorgese** [chingu-voyage4/Bears-Team-6#3]
What are you comfortable with?

What are you not comfortable with but think you can do?

What is something you can absolutely not do?

My goal for this voyage is:

**Comment by kevcomedia** [comment]
**What are you comfortable with?**

* HTML + CSS + JS
* SCSS
* git

**What are you not comfortable with but think you can do?**

* Writing a React app
* Making UI's
* Responsive design
* Making a Node + Express + mongoDB backend
* Data visualization

**What is something you can absolutely not do?**

* Coming up with a design

Maybe not absolutely, but
* Authentication
* Writing (effective) tests

**My goals for this voyage**

* learn how to make a full-stack app
* learn how to build with a team
* finish the project!
