### ISSUE TITLE
Set Individual Goals - Vladimir

### ISSUE THREAD

**Issue by sachamorgese** [chingu-voyage4/Bears-Team-6#4]
What are you comfortable with?

What are you not comfortable with but think you can do?

What is something you can absolutely not do?

My goal for this voyage is:

**Comment by vladimirlogachev** [comment]
**What are you comfortable with?**
Writing words to `describe product` to a customer.
(I'm a salesman for much more time, than a programmer).
Working with `data structures` and `redux` in a functional manner.
Working with events in `saga`. Working with `web-sockets`.
Writing `tests`.
`Designing` a bit.

**What are you not comfortable with but think you can do?**
Don't want to do much with `grids` / `layouts` / `css` / `positioning elements`.
But if strictly necessary, I will slowly do.

**What is something you can absolutely not do?**
Don't want to dive into `backend` before it will be absolutely necessary.

**My goal for this voyage is:**
Have fun and ship an `outstanding app` into the ocean.
