### ISSUE TITLE
Set Individual Goals - Mikeale

### ISSUE THREAD

**Issue by sachamorgese** [chingu-voyage4/Bears-Team-6#5]
What are you comfortable with?

What are you not comfortable with but think you can do?

What is something you can absolutely not do?

My goal for this voyage is:

**Comment by mikeale03** [comment]
What are you comfortable with?
* javascript
* HTML & CSS

What are you not comfortable with but think you can do?
* React+redux
* Back-end development
* TDD

What is something you can absolutely not do?
* Design and layout

My goal?
* Learn team collaboration, Learn with my teammates. Finish project.
