### ISSUE TITLE
Setup JWT on front-end

### ISSUE THREAD

**Issue by sachamorgese** [chingu-voyage4/Bears-Team-6#52]
Implement isAuthenticated in the reducer OK
Save token with login and registration OK
Get authentication on load
Implement logout
Hide routes based on authentication
No login : {
login, registration
}
with login: {
user settings, timestamp, logout
}

**Comment by TheOmegaBlack** [comment]
Implement isAuthenticated in the reducer
Save token with login
Implement logout
Hide routes based on authentication

**Comment by TheOmegaBlack** [comment]
Implement isAuthenticated in the reducer OK
Save token with login OK
Get authentication on load
Implement logout
Hide routes based on authentication
No login : {
login, registration
}
with login: {
user settings, timestamp, logout
}
