### ISSUE TITLE
Set Individual Goals - Tung

### ISSUE THREAD

**Issue by sachamorgese** [chingu-voyage4/Bears-Team-6#6]
What are you comfortable with?

What are you not comfortable with but think you can do?

What is something you can absolutely not do?

My goal for this voyage is:

**Comment by tungnt-580** [comment]
* What are you comfortable with? 
React (+Redux, Redux is something like global state, I don't like to use it, we trying to remove Redux for our project in my company)
Express,  MongoDB/Mongoose, RestAPI
* What are you not comfortable with but think you can do?
Real time action with Socket
Oauth2
* What is something you can absolutely not do?
May be design, I always stuck at first when trying to make something by my own
* My goal for this voyage is
Create full-stack app from scratch
Working with remote team
