### ISSUE TITLE
Define the Stack

### ISSUE THREAD

**Issue by sachamorgese** [chingu-voyage4/Bears-Team-6#7]
We need to define the stack to use for our project.

**Comment by sachamorgese** [comment]
Backend
Node + Express
OAuth
socket.io for events
passport.js - ???

Frontend
React
SASS (or PostCSS, need to decide)
Redux + Saga for state management
socket.io for websockets
axios for http
Webpack

Database
Mongodb
Mongoose??

Other:
ES6
Eslint - airbnb
Flow-type

**Comment by kevcomedia** [comment]
I'm in for mongoose and passport. Still not familiar with socket.io and OAuth.

**Comment by vladimirlogachev** [comment]
I am ok with that

**Comment by mikeale03** [comment]
I think passport.js is good in handling Oauth. I have experiment with socket.io before but don't have a lot of experience. I'm in for express, mongoose and mongodb. no idea with flow-type, airbnb redux-saga.

**Comment by sachamorgese** [comment]
Flow and redux saga are for front-end, no need to worry about that.
Airbnb is just a coding style. Eslint will tell you if something you're doing is wrong, there's nothing much to learn.

socket.io seems to be the biggest issue, but we can work on it together.

**Comment by vladimirlogachev** [comment]
socket.io will be ok.

**Comment by tungnt-580** [comment]
I have no experience with redux-saga, I can learn it. This stack is ok with me

**Comment by mikeale03** [comment]
We are all ok.

**Comment by tungnt-580** [comment]
How about testing? I suggest using mocha and chai, they are very common tools for Unit testing

**Comment by sachamorgese** [comment]
I'm fine with mocha and chai. I don't have experience with them, but I'll happily check them out.

Let's put socket.io in. If we see we're unable to use it, we might move its implementation to the post MVP.

I'm closing the issue and advancing the milestone. Great job guys!
