### ISSUE TITLE
Define the WorkFlow/Setup Development

### ISSUE THREAD

**Issue by sachamorgese** [chingu-voyage4/Bears-Team-6#8]
We need to define the development Workflow and set it up.

**Comment by mikeale03** [comment]
I mistakenly press close.

**Comment by vladimirlogachev** [comment]
I need frontend to be a repo.
and backend to always fetch and build *frontend/master*.

**Comment by sachamorgese** [comment]
Project Management: 	Waffle
Standups:		Slack
Text communication:	Discord
Pair-programming:	TeamViewer
Vocal communication:	Skype / Discord
